export interface Inst {
  Inst_id: number;
  Inst_nm: string;
  Alias_nm: string;
  Coll_nm: string;
  Pg_inst: number;
  Hosp_nm: string;
  Add1: string;
  Add2: string;
  Add3: string;
  City: string;
  Mobile: string;
  Email: string;
  Phone: string;
  Active: boolean;
  Pfno: string;
  Desg: string;
  En: string;
  Amp_pan_no: string;
  Amp_tds_no: string;
  Amp_tds_c: string;
  F16_person: string;
  F16_parent: string;
  F16_desg: string;
  Inst_cd: string;
  Sign1: string;
  Sign2: string;
  Sign3: string;
  Sign4: string;
  Sign5: string;
  Sign6: string;
  Stud: boolean;
  Host: boolean;
  Stor: boolean;
  Payr: boolean;
  Acnt: boolean;
  Tally_cmp: string;
  Gst_no: string;
  Pan: string;
  Bank_name: string;
  Bank_acno: string;
  Bank_ifsc: string;
  Smc_nm: string;
  Latefee: boolean | null;
  Hospital: boolean | null;
  College: boolean | null;
}
